### ISSUE TITLE
Playable as web application?

### ISSUE THREAD

**Issue by amo13** [catabriga/graphwar#8]
This looks amazing! Needing to execute a jar file with java is somewhat of a hassle though. I don't know java, is it possible to turn thus into a web application that people could play in their web browsers?

**Comment by catabriga** [comment]
The game was originally a web application (a Java applet). However nowadays java applets are mostly blocked on all browsers due to security reasons, so that became a bigger hassle than just having it be a standalone application. If you want an easier way to launch the game, it is also available on steam, where it is pretty straight forward to launch:
https://store.steampowered.com/app/1899700/Graphwar/

**Comment by amo13** [comment]
Thank you!
